[package]
name = "bass-rs"
version = "1.0.0"
authors = ["KernelError <villainkernelerror@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bass-sys = "1.1.3"